<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterDiagnosa;

class DiagnosaICD10ExtendedSeeder extends Seeder
{
    /**
     * Tambahan diagnosa ICD-10 kategori: Neoplasm, Trauma, Musculoskeletal, Skin, dll
     * Sumber: WHO ICD-10 Classification
     */
    public function run(): void
    {
        $diagnoses = [
            // === NEOPLASMA / KANKER (C00-C97) ===
            ['kode' => 'C00', 'nama' => 'Malignant neoplasm of lip, oral cavity, and pharynx'],
            ['kode' => 'C00.0', 'nama' => 'Malignant neoplasm of external upper lip'],
            ['kode' => 'C00.1', 'nama' => 'Malignant neoplasm of external lower lip'],
            ['kode' => 'C00.8', 'nama' => 'Malignant neoplasm of overlapping sites of lip, oral cavity, and pharynx'],
            ['kode' => 'C00.9', 'nama' => 'Malignant neoplasm of lip, oral cavity, and pharynx, unspecified'],
            ['kode' => 'C15', 'nama' => 'Malignant neoplasm of oesophagus (kanker kerongkongan)'],
            ['kode' => 'C16', 'nama' => 'Malignant neoplasm of stomach (kanker lambung)'],
            ['kode' => 'C18', 'nama' => 'Malignant neoplasm of colon (kanker usus besar)'],
            ['kode' => 'C19', 'nama' => 'Malignant neoplasm of rectosigmoid junction'],
            ['kode' => 'C20', 'nama' => 'Malignant neoplasm of rectum (kanker rectum)'],
            ['kode' => 'C22', 'nama' => 'Malignant neoplasm of liver and intrahepatic bile ducts (kanker hati)'],
            ['kode' => 'C25', 'nama' => 'Malignant neoplasm of pancreas (kanker pankreas)'],
            ['kode' => 'C34', 'nama' => 'Malignant neoplasm of unspecified part of unspecified bronchus or lung (kanker paru)'],
            ['kode' => 'C43', 'nama' => 'Melanoma of skin'],
            ['kode' => 'C50', 'nama' => 'Malignant neoplasm of breast (kanker payudara)'],
            ['kode' => 'C53', 'nama' => 'Malignant neoplasm of cervix uteri (kanker serviks)'],
            ['kode' => 'C54', 'nama' => 'Malignant neoplasm of corpus uteri'],
            ['kode' => 'C56', 'nama' => 'Malignant neoplasm of ovary'],
            ['kode' => 'C61', 'nama' => 'Malignant neoplasm of prostate (kanker prostat)'],
            ['kode' => 'C67', 'nama' => 'Malignant neoplasm of bladder (kanker kandung kemih)'],
            ['kode' => 'C73', 'nama' => 'Malignant neoplasm of thyroid gland (kanker tiroid)'],
            ['kode' => 'C81', 'nama' => 'Hodgkin lymphoma'],
            ['kode' => 'C82', 'nama' => 'Follicular (nodular) lymphoma'],
            ['kode' => 'C91', 'nama' => 'Lymphoid leukemia (leukemia limfoid)'],
            ['kode' => 'C92', 'nama' => 'Myeloid leukemia (leukemia myeloid)'],

            // === CEDERA, KERACUNAN, KOMPLIKASI (S00-T98) ===
            ['kode' => 'S00', 'nama' => 'Superficial injury of head'],
            ['kode' => 'S01', 'nama' => 'Open wound of head'],
            ['kode' => 'S02', 'nama' => 'Fracture of skull and facial bones (fraktur tengkorak)'],
            ['kode' => 'S06', 'nama' => 'Intracranial injury (cedera intrakranial)'],
            ['kode' => 'S12', 'nama' => 'Fracture of neck (fraktur leher)'],
            ['kode' => 'S22', 'nama' => 'Fracture of rib(s), sternum, and thoracic spine (fraktur tulang rusuk)'],
            ['kode' => 'S32', 'nama' => 'Fracture of lumbar spine and pelvis (fraktur lumbar dan pelvis)'],
            ['kode' => 'S42', 'nama' => 'Fracture of shoulder and upper arm (fraktur bahu dan lengan atas)'],
            ['kode' => 'S52', 'nama' => 'Fracture of forearm (fraktur lengan bawah)'],
            ['kode' => 'S62', 'nama' => 'Fracture at wrist and hand level'],
            ['kode' => 'S72', 'nama' => 'Fracture of femur (fraktur paha)'],
            ['kode' => 'S82', 'nama' => 'Fracture of lower leg, including ankle (fraktur kaki)'],
            ['kode' => 'S92', 'nama' => 'Fracture of foot'],
            ['kode' => 'T20', 'nama' => 'Burn of head, face, and neck (luka bakar kepala)'],
            ['kode' => 'T30', 'nama' => 'Burn of unspecified body region (luka bakar umum)'],
            ['kode' => 'T36', 'nama' => 'Poisoning by antibiotics (keracunan antibiotik)'],
            ['kode' => 'T50', 'nama' => 'Poisoning by diuretics and other and unspecified drugs, medicaments, and biological substances'],

            // === PENYAKIT MUSCULOSKELETAL (M00-M99) ===
            ['kode' => 'M05', 'nama' => 'Rheumatoid arthritis (arthritis rheumatoid)'],
            ['kode' => 'M06', 'nama' => 'Other specified inflammatory polyarthropathies'],
            ['kode' => 'M10', 'nama' => 'Gout (penyakit pirai/gout)'],
            ['kode' => 'M15', 'nama' => 'Polyosteoarthritis (poliosteoartritis)'],
            ['kode' => 'M16', 'nama' => 'Primary osteoarthritis of hip'],
            ['kode' => 'M17', 'nama' => 'Primary osteoarthritis of knee (osteoarthritis lutut)'],
            ['kode' => 'M19', 'nama' => 'Primary osteoarthritis of other sites'],
            ['kode' => 'M20', 'nama' => 'Deformities of toe(s) (acquired)'],
            ['kode' => 'M21', 'nama' => 'Other acquired deformities of limbs'],
            ['kode' => 'M25', 'nama' => 'Other joint disorders, not elsewhere classified'],
            ['kode' => 'M30', 'nama' => 'Polyarteritis nodosa and related conditions (poliarteritis)'],
            ['kode' => 'M31', 'nama' => 'Other necrotizing vasculitides'],
            ['kode' => 'M32', 'nama' => 'Systemic lupus erythematosus [SLE] (lupus)'],
            ['kode' => 'M33', 'nama' => 'Dermatomyositis'],
            ['kode' => 'M34', 'nama' => 'Systemic sclerosis [scleroderma]'],
            ['kode' => 'M35', 'nama' => 'Other systemic involvement of connective tissue'],
            ['kode' => 'M40', 'nama' => 'Kyphosis and lordosis (kelainan kurva tulang belakang)'],
            ['kode' => 'M41', 'nama' => 'Scoliosis (skoliosis/kelainan lengkungan tulang belakang)'],
            ['kode' => 'M42', 'nama' => 'Spinal osteochondrosis'],
            ['kode' => 'M45', 'nama' => 'Ankylosing spondylitis (ankilosis spondilitis)'],
            ['kode' => 'M47', 'nama' => 'Spondylosis (spondilosis)'],
            ['kode' => 'M50', 'nama' => 'Cervical disc disorders'],
            ['kode' => 'M51', 'nama' => 'Thoracic, thoracolumbar and lumbosacral intervertebral disc disorders (hernia disc)'],
            ['kode' => 'M54', 'nama' => 'Dorsalgia (back pain/nyeri punggung)'],
            ['kode' => 'M79', 'nama' => 'Other and unspecified soft tissue disorders, not elsewhere classified'],
            ['kode' => 'M80', 'nama' => 'Osteoporosis with current pathological fracture'],
            ['kode' => 'M81', 'nama' => 'Osteoporosis without current pathological fracture (osteoporosis)'],

            // === PENYAKIT KULIT (L00-L99) ===
            ['kode' => 'L01', 'nama' => 'Impetigo (impetigo)'],
            ['kode' => 'L02', 'nama' => 'Skin abscess, furuncle and carbuncle (abses kulit)'],
            ['kode' => 'L03', 'nama' => 'Cellulitis (cellulitis/selulitis)'],
            ['kode' => 'L04', 'nama' => 'Acute lymphadenitis'],
            ['kode' => 'L05', 'nama' => 'Pilonidal cyst'],
            ['kode' => 'L08', 'nama' => 'Other local infections of skin and subcutaneous tissue'],
            ['kode' => 'L20', 'nama' => 'Atopic dermatitis (eczema/eksema)'],
            ['kode' => 'L21', 'nama' => 'Seborrheic dermatitis'],
            ['kode' => 'L22', 'nama' => 'Diaper dermatitis'],
            ['kode' => 'L23', 'nama' => 'Allergic contact dermatitis (dermatitis alergi)'],
            ['kode' => 'L24', 'nama' => 'Irritant contact dermatitis'],
            ['kode' => 'L25', 'nama' => 'Unspecified contact dermatitis'],
            ['kode' => 'L26', 'nama' => 'Exfoliative dermatitis'],
            ['kode' => 'L27', 'nama' => 'Dermatitis due to substances taken internally'],
            ['kode' => 'L28', 'nama' => 'Lichen simplex chronicus and prurigo'],
            ['kode' => 'L29', 'nama' => 'Pruritus (gatal-gatal)'],
            ['kode' => 'L30', 'nama' => 'Other dermatitis'],
            ['kode' => 'L40', 'nama' => 'Psoriasis (psoriasis)'],
            ['kode' => 'L41', 'nama' => 'Pityriasis rubra pilaris'],
            ['kode' => 'L43', 'nama' => 'Lichen planus'],
            ['kode' => 'L44', 'nama' => 'Other papulosquamous disorders'],
            ['kode' => 'L45', 'nama' => 'Papulosquamous disorders in diseases classified elsewhere'],
            ['kode' => 'L49', 'nama' => 'Exfoliation due to erythematous conditions'],
            ['kode' => 'L50', 'nama' => 'Urticaria (urtikaria/kemerahan kulit)'],
            ['kode' => 'L51', 'nama' => 'Erythema multiforme'],
            ['kode' => 'L52', 'nama' => 'Erythema nodosum'],
            ['kode' => 'L53', 'nama' => 'Other erythematous conditions'],
            ['kode' => 'L54', 'nama' => 'Erythema in diseases classified elsewhere'],
            ['kode' => 'L55', 'nama' => 'Sunburn'],
            ['kode' => 'L56', 'nama' => 'Other acute skin changes due to ultraviolet radiation'],
            ['kode' => 'L57', 'nama' => 'Skin changes due to chronic exposure to nonionizing radiation'],
            ['kode' => 'L58', 'nama' => 'Radiodermatitis'],
            ['kode' => 'L59', 'nama' => 'Unspecified disorder of skin and subcutaneous tissue related to radiation'],
            ['kode' => 'L60', 'nama' => 'Nail disorders'],
            ['kode' => 'L70', 'nama' => 'Acne (jerawat)'],
            ['kode' => 'L71', 'nama' => 'Rosacea'],
            ['kode' => 'L72', 'nama' => 'Follicular cysts of skin and subcutaneous tissue'],
            ['kode' => 'L73', 'nama' => 'Other follicular disorders'],
            ['kode' => 'L74', 'nama' => 'Eccrine sweat disorders'],
            ['kode' => 'L75', 'nama' => 'Apocrine sweat disorders'],
            ['kode' => 'L80', 'nama' => 'Vitiligo'],
            ['kode' => 'L81', 'nama' => 'Other disorders of pigmentation'],
            ['kode' => 'L82', 'nama' => 'Seborrheic keratosis'],
            ['kode' => 'L83', 'nama' => 'Acanthosis nigricans'],
            ['kode' => 'L84', 'nama' => 'Corns and calluses'],
            ['kode' => 'L85', 'nama' => 'Other epidermal thickening'],
            ['kode' => 'L86', 'nama' => 'Keratoderma in diseases classified elsewhere'],
            ['kode' => 'L87', 'nama' => 'Transepidermal elimination disorders'],
            ['kode' => 'L88', 'nama' => 'Pyogenic granuloma'],
            ['kode' => 'L89', 'nama' => 'Pressure ulcer (pressure sore/luka tekan)'],
            ['kode' => 'L90', 'nama' => 'Atrophic disorders of skin'],
            ['kode' => 'L91', 'nama' => 'Hypertrophic disorders of the skin'],
            ['kode' => 'L92', 'nama' => 'Granulomatous disorders of the skin and subcutaneous tissue'],
            ['kode' => 'L93', 'nama' => 'Lupus and related conditions'],
            ['kode' => 'L94', 'nama' => 'Other localized connective tissue disorders'],
            ['kode' => 'L95', 'nama' => 'Vasculitis limited to the skin, not elsewhere classified'],
            ['kode' => 'L97', 'nama' => 'Non-pressure chronic ulcer of lower limb, not elsewhere classified (borok)'],
            ['kode' => 'L98', 'nama' => 'Other disorders of the skin and subcutaneous tissue, not elsewhere classified'],
            ['kode' => 'L99', 'nama' => 'Skin and subcutaneous tissue disorders in diseases classified elsewhere'],

            // === PENYAKIT SISTEM GENITOURINARI (N00-N99) ===
            ['kode' => 'N00', 'nama' => 'Acute nephritic syndrome'],
            ['kode' => 'N01', 'nama' => 'Rapidly progressive nephritic syndrome'],
            ['kode' => 'N02', 'nama' => 'Recurrent and persistent hematuria'],
            ['kode' => 'N03', 'nama' => 'Chronic nephritic syndrome'],
            ['kode' => 'N04', 'nama' => 'Nephrotic syndrome'],
            ['kode' => 'N05', 'nama' => 'Unspecified nephritic syndrome'],
            ['kode' => 'N10', 'nama' => 'Acute tubulo-interstitial nephritis (pielonefritis akut)'],
            ['kode' => 'N11', 'nama' => 'Chronic tubulo-interstitial nephritis'],
            ['kode' => 'N12', 'nama' => 'Tubulo-interstitial nephritis, not specified as acute or chronic'],
            ['kode' => 'N13', 'nama' => 'Obstructive and reflux uropathy'],
            ['kode' => 'N15', 'nama' => 'Other chronic renal failure'],
            ['kode' => 'N18', 'nama' => 'Chronic kidney disease [CKD] (penyakit ginjal kronis)'],
            ['kode' => 'N19', 'nama' => 'Unspecified kidney failure'],
            ['kode' => 'N20', 'nama' => 'Calculus of kidney and ureter (batu ginjal)'],
            ['kode' => 'N21', 'nama' => 'Calculus of lower urinary tract'],
            ['kode' => 'N30', 'nama' => 'Cystitis (sistitis/infeksi kandung kemih)'],
            ['kode' => 'N31', 'nama' => 'Neuromuscular dysfunction of bladder'],
            ['kode' => 'N32', 'nama' => 'Bladder neck obstruction'],
            ['kode' => 'N33', 'nama' => 'Bladder disorders in diseases classified elsewhere'],
            ['kode' => 'N34', 'nama' => 'Urethritis and urethral syndrome'],
            ['kode' => 'N35', 'nama' => 'Urethral stricture'],
            ['kode' => 'N36', 'nama' => 'Urethral fistula'],
            ['kode' => 'N37', 'nama' => 'Urethral disorder, unspecified'],
            ['kode' => 'N39', 'nama' => 'Other disorders of urinary system'],
            ['kode' => 'N40', 'nama' => 'Hyperplasia of prostate (hiperplasia prostat)'],
            ['kode' => 'N41', 'nama' => 'Inflammatory diseases of prostate (prostatitis)'],
            ['kode' => 'N42', 'nama' => 'Chlamydial infection of lower genitourinary tract'],
            ['kode' => 'N43', 'nama' => 'Hydrocele and spermatocele'],
            ['kode' => 'N44', 'nama' => 'Spermatocele'],
            ['kode' => 'N45', 'nama' => 'Orchitis and epididymitis (orkitis/radang buah pelir)'],
            ['kode' => 'N46', 'nama' => 'Male infertility'],
            ['kode' => 'N47', 'nama' => 'Redundant prepuce and phimosis'],
            ['kode' => 'N48', 'nama' => 'Other disorders of penis'],
            ['kode' => 'N49', 'nama' => 'Inflammatory disorders of male genital organs'],
            ['kode' => 'N50', 'nama' => 'Other and unspecified male genital disorders'],
            ['kode' => 'N51', 'nama' => 'Disorders of male genital organs in diseases classified elsewhere'],
            ['kode' => 'N60', 'nama' => 'Benign mammary dysplasia'],
            ['kode' => 'N61', 'nama' => 'Inflammatory disorders of breast'],
            ['kode' => 'N62', 'nama' => 'Hypertrophy of breast'],
            ['kode' => 'N63', 'nama' => 'Unspecified lump in breast'],
            ['kode' => 'N64', 'nama' => 'Other disorders of breast'],
            ['kode' => 'N70', 'nama' => 'Salpingitis and oophoritis'],
            ['kode' => 'N71', 'nama' => 'Inflammatory disease of uterus, except cervix'],
            ['kode' => 'N72', 'nama' => 'Inflammatory disease of cervix uteri'],
            ['kode' => 'N73', 'nama' => 'Other female pelvic inflammatory diseases'],
            ['kode' => 'N74', 'nama' => 'Female pelvic inflammatory disorders in diseases classified elsewhere'],
            ['kode' => 'N75', 'nama' => 'Diseases of Bartholin gland'],
            ['kode' => 'N76', 'nama' => 'Other inflammation of vagina and vulva'],
            ['kode' => 'N77', 'nama' => 'Ulceration and inflammation of vagina and vulva in diseases classified elsewhere'],
            ['kode' => 'N80', 'nama' => 'Endometriosis'],
            ['kode' => 'N81', 'nama' => 'Female genital prolapse'],
            ['kode' => 'N82', 'nama' => 'Fistulae involving female genital tract'],
            ['kode' => 'N83', 'nama' => 'Noninflammatory disorders of ovary, fallopian tube and broad ligament'],
            ['kode' => 'N84', 'nama' => 'Polyp of female genital tract'],
            ['kode' => 'N85', 'nama' => 'Other noninflammatory disorders of uterus, except cervix'],
            ['kode' => 'N86', 'nama' => 'Erosion and ectropion of cervix uteri'],
            ['kode' => 'N87', 'nama' => 'Dysplasia of cervix uteri'],
            ['kode' => 'N88', 'nama' => 'Other noninflammatory disorders of cervix uteri'],
            ['kode' => 'N89', 'nama' => 'Other noninflammatory disorders of vagina'],
            ['kode' => 'N90', 'nama' => 'Other noninflammatory disorders of vulva and perineum'],
            ['kode' => 'N91', 'nama' => 'Absent, scanty and rare menstruation (amenorea)'],
            ['kode' => 'N92', 'nama' => 'Excessive, frequent and irregular menstruation (menorhagia)'],
            ['kode' => 'N93', 'nama' => 'Other abnormal uterine and vaginal bleeding'],
            ['kode' => 'N94', 'nama' => 'Pain and other conditions associated with female genital organs and menstrual cycle'],
            ['kode' => 'N95', 'nama' => 'Menopausal and other perimenopausal disorders (menopause)'],
            ['kode' => 'N96', 'nama' => 'Recurrent pregnancy loss'],
            ['kode' => 'N97', 'nama' => 'Female infertility'],
            ['kode' => 'N98', 'nama' => 'Complications associated with artificial fertilization'],
            ['kode' => 'N99', 'nama' => 'Postprocedural disorders of genitourinary system, not elsewhere classified'],
        ];

        // Gunakan updateOrCreate agar tidak duplikat
        foreach ($diagnoses as $diagnosis) {
            MasterDiagnosa::updateOrCreate(
                ['kode' => $diagnosis['kode']],
                ['nama' => $diagnosis['nama']]
            );
        }

        echo "\n✓ Seeding diagnosa ICD-10 extended selesai (" . count($diagnoses) . " entri tambahan)\n";
        echo "  Total diagnosa di database: " . MasterDiagnosa::count() . "\n";
    }
}
