<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterDiagnosa;

class DiagnosaICD10Seeder extends Seeder
{
    /**
     * Seed diagnosa dengan kode ICD-10 resmi dari WHO
     * Sumber: https://www.who.int/standards/classifications/classification-of-diseases
     */
    public function run(): void
    {
        $diagnoses = [
            // === PENYAKIT MENULAR (A00-B99) ===
            ['kode' => 'A00', 'nama' => 'Kolera'],
            ['kode' => 'A00.0', 'nama' => 'Kolera dengan choleraic enteritis'],
            ['kode' => 'A00.1', 'nama' => 'Kolera El Tor'],
            ['kode' => 'A01', 'nama' => 'Tifoid dan paratifoid'],
            ['kode' => 'A01.0', 'nama' => 'Tifoid demam'],
            ['kode' => 'A01.1', 'nama' => 'Paratifoid demam A'],
            ['kode' => 'A01.2', 'nama' => 'Paratifoid demam B'],
            ['kode' => 'A01.3', 'nama' => 'Paratifoid demam C'],
            ['kode' => 'A01.4', 'nama' => 'Paratifoid demam, tidak tergolongkan'],
            ['kode' => 'A02', 'nama' => 'Infeksi Salmonella'],
            ['kode' => 'A02.0', 'nama' => 'Salmonella enteritis'],
            ['kode' => 'A02.1', 'nama' => 'Salmonella septicemia'],
            ['kode' => 'A02.2', 'nama' => 'Salmonella localized infection'],
            ['kode' => 'A02.8', 'nama' => 'Infeksi Salmonella lainnya'],
            ['kode' => 'A02.9', 'nama' => 'Infeksi Salmonella, tidak tergolongkan'],
            ['kode' => 'A03', 'nama' => 'Shigellosis'],
            ['kode' => 'A03.0', 'nama' => 'Shigellosis disebabkan Shigella dysenteriae'],
            ['kode' => 'A03.1', 'nama' => 'Shigellosis disebabkan Shigella flexneri'],
            ['kode' => 'A03.2', 'nama' => 'Shigellosis disebabkan Shigella boydii'],
            ['kode' => 'A03.3', 'nama' => 'Shigellosis disebabkan Shigella sonnei'],
            ['kode' => 'A03.8', 'nama' => 'Shigellosis lainnya'],
            ['kode' => 'A03.9', 'nama' => 'Shigellosis, tidak tergolongkan'],
            ['kode' => 'A04', 'nama' => 'Infeksi bakteri foodborne lainnya'],
            ['kode' => 'A04.0', 'nama' => 'Infeksi Campylobacter'],
            ['kode' => 'A04.1', 'nama' => 'Infeksi Vibrio lainnya'],
            ['kode' => 'A04.2', 'nama' => 'Infeksi Bacillus cereus'],
            ['kode' => 'A04.3', 'nama' => 'Infeksi Clostridium perfringens'],
            ['kode' => 'A04.4', 'nama' => 'Infeksi Vibrio vulnificus'],
            ['kode' => 'A04.5', 'nama' => 'Infeksi Clostridium botulinum'],
            ['kode' => 'A04.6', 'nama' => 'Infeksi Staphylococcus aureus'],
            ['kode' => 'A04.7', 'nama' => 'Infeksi Listeria monocytogenes'],
            ['kode' => 'A04.8', 'nama' => 'Foodborne bakteri infeksi lainnya'],
            ['kode' => 'A04.9', 'nama' => 'Foodborne bakteri infeksi, tidak tergolongkan'],

            // === DIARE DAN GASTROENTERITIS (A06-A09) ===
            ['kode' => 'A06', 'nama' => 'Amebiasis'],
            ['kode' => 'A06.0', 'nama' => 'Disentri ameba akut'],
            ['kode' => 'A06.1', 'nama' => 'Amebiasis kronis usus'],
            ['kode' => 'A06.2', 'nama' => 'Amebiasis usus tidak tergolongkan'],
            ['kode' => 'A06.3', 'nama' => 'Ameba liver abscess'],
            ['kode' => 'A06.4', 'nama' => 'Amebiasis paru-paru'],
            ['kode' => 'A06.5', 'nama' => 'Amebiasis brain'],
            ['kode' => 'A06.6', 'nama' => 'Amebiasis kulit'],
            ['kode' => 'A06.8', 'nama' => 'Amebiasis lainnya'],
            ['kode' => 'A06.9', 'nama' => 'Amebiasis tidak tergolongkan'],
            ['kode' => 'A07', 'nama' => 'Parasit lainnya yang dapat menyebabkan diare dan kolitis'],
            ['kode' => 'A07.0', 'nama' => 'Balantidiasis'],
            ['kode' => 'A07.1', 'nama' => 'Giardiasis (lambliasis)'],
            ['kode' => 'A07.2', 'nama' => 'Cryptosporidiosis'],
            ['kode' => 'A07.3', 'nama' => 'Cyclosporiasis'],
            ['kode' => 'A07.4', 'nama' => 'Isosporiasis'],
            ['kode' => 'A07.8', 'nama' => 'Parasit intestinal lainnya'],
            ['kode' => 'A07.9', 'nama' => 'Parasit intestinal tidak tergolongkan'],
            ['kode' => 'A08', 'nama' => 'Infeksi virus yang disertai gastroenteritis'],
            ['kode' => 'A08.0', 'nama' => 'Rotavirus enteritis'],
            ['kode' => 'A08.1', 'nama' => 'Norovirus enteritis'],
            ['kode' => 'A08.2', 'nama' => 'Adenovirus enteritis'],
            ['kode' => 'A08.3', 'nama' => 'Astrovirus enteritis'],
            ['kode' => 'A08.4', 'nama' => 'Enterovirus enteritis'],
            ['kode' => 'A08.5', 'nama' => 'Sapovirus enteritis'],
            ['kode' => 'A08.8', 'nama' => 'Infeksi virus lainnya dengan gastroenteritis'],
            ['kode' => 'A08.9', 'nama' => 'Infeksi virus tidak tergolongkan dengan gastroenteritis'],
            ['kode' => 'A09', 'nama' => 'Diare dan gastroenteritis asal infeksi'],
            ['kode' => 'A09.0', 'nama' => 'Diare dan gastroenteritis (noninfeksi)'],
            ['kode' => 'A09.9', 'nama' => 'Diare dan gastroenteritis asal infeksi tidak tergolongkan'],

            // === PENYAKIT MENULAR SALURAN PERNAFASAN (J00-J99) ===
            ['kode' => 'J00', 'nama' => 'Akut nasofaring (rhinitis akut)'],
            ['kode' => 'J01', 'nama' => 'Akut sinusitis'],
            ['kode' => 'J02', 'nama' => 'Akut faringitis'],
            ['kode' => 'J03', 'nama' => 'Akut tonsilitis'],
            ['kode' => 'J04', 'nama' => 'Akut laryngitis dan tracheitis'],
            ['kode' => 'J05', 'nama' => 'Akut obstructive laryngitis (croup) dan epiglottitis'],
            ['kode' => 'J06', 'nama' => 'Akut infeksi saluran pernafasan atas tidak tergolongkan'],
            ['kode' => 'J06.0', 'nama' => 'Akut nasofaring campuran, faringitis dan tonsilitis'],
            ['kode' => 'J06.8', 'nama' => 'Penyakit saluran pernafasan atas lainnya'],
            ['kode' => 'J06.9', 'nama' => 'Akut infeksi saluran pernafasan atas tidak tergolongkan'],
            ['kode' => 'J09', 'nama' => 'Influenza dengan pneumonia lainnya'],
            ['kode' => 'J10', 'nama' => 'Influenza karena virus influenza (dengan manifestasi respiratori)'],
            ['kode' => 'J11', 'nama' => 'Influenza virus tidak tergolongkan (dengan manifestasi respiratori)'],
            ['kode' => 'J12', 'nama' => 'Viral pneumonia tidak tergolongkan sebagai influenza'],
            ['kode' => 'J13', 'nama' => 'Pneumonia pneumococcal'],
            ['kode' => 'J14', 'nama' => 'Pneumonia Haemophilus influenzae'],
            ['kode' => 'J15', 'nama' => 'Bakteri pneumonia lainnya'],
            ['kode' => 'J18', 'nama' => 'Pneumonia tidak tergolongkan'],

            // === PENYAKIT JANTUNG (I00-I99) ===
            ['kode' => 'I10', 'nama' => 'Hipertensi (penyakit tekanan darah tinggi) essential (primary)'],
            ['kode' => 'I11', 'nama' => 'Penyakit jantung hipertensif'],
            ['kode' => 'I12', 'nama' => 'Penyakit ginjal kronis hipertensif'],
            ['kode' => 'I13', 'nama' => 'Penyakit jantung dan ginjal hipertensif'],
            ['kode' => 'I20', 'nama' => 'Angina pectoris'],
            ['kode' => 'I21', 'nama' => 'Infark miokard akut (serangan jantung)'],
            ['kode' => 'I22', 'nama' => 'Infark miokard ulang'],
            ['kode' => 'I23', 'nama' => 'Komplikasi dini infark miokard akut'],
            ['kode' => 'I24', 'nama' => 'Kondisi pasca infark miokard'],
            ['kode' => 'I25', 'nama' => 'Penyakit jantung iskemik kronis'],
            ['kode' => 'I30', 'nama' => 'Perikarditis akut'],
            ['kode' => 'I31', 'nama' => 'Penyakit perikard kronis'],
            ['kode' => 'I32', 'nama' => 'Perikarditis dalam penyakit klasifikasi lainnya'],
            ['kode' => 'I40', 'nama' => 'Myokarditis akut'],
            ['kode' => 'I41', 'nama' => 'Myokarditis dalam penyakit klasifikasi lainnya'],
            ['kode' => 'I42', 'nama' => 'Kardiomiopati'],
            ['kode' => 'I50', 'nama' => 'Gagal jantung'],

            // === PENYAKIT ENDOKRIN, NUTRISI (E00-E99) ===
            ['kode' => 'E10', 'nama' => 'Diabetes mellitus tergantung insulin'],
            ['kode' => 'E11', 'nama' => 'Diabetes mellitus tidak tergantung insulin (tipe 2)'],
            ['kode' => 'E12', 'nama' => 'Diabetes mellitus malnutrisi-related'],
            ['kode' => 'E13', 'nama' => 'Diabetes mellitus lainnya'],
            ['kode' => 'E14', 'nama' => 'Diabetes mellitus tidak tergolongkan'],
            ['kode' => 'E20', 'nama' => 'Hipoparatiroidisme'],
            ['kode' => 'E21', 'nama' => 'Hiperparatiroidisme dan kelainan paratiroid lainnya'],
            ['kode' => 'E23', 'nama' => 'Kelainan pituitary dan hypothalamic'],
            ['kode' => 'E24', 'nama' => 'Cushing syndrome'],
            ['kode' => 'E25', 'nama' => 'Kelainan adrenal'],
            ['kode' => 'E26', 'nama' => 'Hiperaldosteronisme'],
            ['kode' => 'E27', 'nama' => 'Insufisiensi korteks adrenal'],
            ['kode' => 'E29', 'nama' => 'Testicular dysfunction'],
            ['kode' => 'E30', 'nama' => 'Kelainan ovarium, fallopian tube, dan ligamen uteri'],
            ['kode' => 'E34', 'nama' => 'Kelainan endokrin lainnya'],
            ['kode' => 'E40', 'nama' => 'Kwashiorkor'],
            ['kode' => 'E41', 'nama' => 'Malnutrisi protein-kalori sedang'],
            ['kode' => 'E42', 'nama' => 'Malnutrisi protein-kalori ringan'],
            ['kode' => 'E43', 'nama' => 'Malnutrisi tidak tergolongkan'],
            ['kode' => 'E44', 'nama' => 'Malnutrisi protein-kalori'],
            ['kode' => 'E45', 'nama' => 'Delayed development following protein-energy malnutrition'],
            ['kode' => 'E46', 'nama' => 'Protein-energy malnutrition tidak tergolongkan'],
            ['kode' => 'E50', 'nama' => 'Vitamin A deficiency'],
            ['kode' => 'E51', 'nama' => 'Thiamine deficiency'],
            ['kode' => 'E52', 'nama' => 'Niacin deficiency'],
            ['kode' => 'E53', 'nama' => 'Deficiency of other B group vitamins'],
            ['kode' => 'E54', 'nama' => 'Ascorbic acid deficiency'],
            ['kode' => 'E55', 'nama' => 'Vitamin D deficiency'],
            ['kode' => 'E56', 'nama' => 'Vitamin E and K deficiency'],
            ['kode' => 'E58', 'nama' => 'Dietary calcium deficiency'],
            ['kode' => 'E59', 'nama' => 'Dietary selenium deficiency'],
            ['kode' => 'E60', 'nama' => 'Dietary zinc deficiency'],
            ['kode' => 'E61', 'nama' => 'Deficiency of other nutrient elements'],
            ['kode' => 'E62', 'nama' => 'Overweight, obesity and excessive food intake'],
            ['kode' => 'E63', 'nama' => 'Other nutritional deficiencies'],
            ['kode' => 'E64', 'nama' => 'Sequelae of malnutrition and other nutritional deficiencies'],
            ['kode' => 'E65', 'nama' => 'Localized adiposity'],
            ['kode' => 'E66', 'nama' => 'Obesity'],
            ['kode' => 'E67', 'nama' => 'Overeating'],
            ['kode' => 'E68', 'nama' => 'Excessive food intake'],
            ['kode' => 'E70', 'nama' => 'Disorders of aromatic amino-acid metabolism'],
            ['kode' => 'E71', 'nama' => 'Disorders of branched-chain amino-acid metabolism and fatty-acid oxidation'],
            ['kode' => 'E72', 'nama' => 'Other disorders of amino-acid metabolism'],
            ['kode' => 'E73', 'nama' => 'Lactose intolerance'],
            ['kode' => 'E74', 'nama' => 'Other carbohydrate malabsorption'],
            ['kode' => 'E75', 'nama' => 'Disorders of sphingolipid metabolism and other lipid storage disorders'],
            ['kode' => 'E76', 'nama' => 'Disorders of glycosaminoglycan metabolism and other connective-tissue disorders'],
            ['kode' => 'E77', 'nama' => 'Disorders of carbohydrate metabolism not elsewhere classified'],
            ['kode' => 'E78', 'nama' => 'Abdominal and pelvic pain'],
            ['kode' => 'E79', 'nama' => 'Disorders of purine and pyrimidine metabolism'],
            ['kode' => 'E80', 'nama' => 'Disorders of porphyrin and bilirubin metabolism'],
            ['kode' => 'E83', 'nama' => 'Disorders of mineral metabolism'],
            ['kode' => 'E84', 'nama' => 'Cystic fibrosis'],
            ['kode' => 'E85', 'nama' => 'Amyloidosis'],
            ['kode' => 'E86', 'nama' => 'Volume depletion'],
            ['kode' => 'E87', 'nama' => 'Hyperosmolality and hypernatremia'],
            ['kode' => 'E88', 'nama' => 'Other metabolic disorders'],
            ['kode' => 'E89', 'nama' => 'Postprocedural endocrine and metabolic complications and disorders, not elsewhere classified'],
            ['kode' => 'E90', 'nama' => 'Nutritional deficiencies, not elsewhere classified'],

            // === PENYAKIT MENTAL (F00-F99) ===
            ['kode' => 'F01', 'nama' => 'Vascular dementia'],
            ['kode' => 'F02', 'nama' => 'Dementia in diseases classified elsewhere'],
            ['kode' => 'F03', 'nama' => 'Unspecified dementia'],
            ['kode' => 'F05', 'nama' => 'Delirium not induced by alcohol and other psychoactive substances'],
            ['kode' => 'F10', 'nama' => 'Mental and behavioural disorders due to use of alcohol'],
            ['kode' => 'F20', 'nama' => 'Schizophrenia'],
            ['kode' => 'F30', 'nama' => 'Manic episode'],
            ['kode' => 'F31', 'nama' => 'Bipolar affective disorder'],
            ['kode' => 'F32', 'nama' => 'Depressive episode'],
            ['kode' => 'F33', 'nama' => 'Recurrent depressive disorder'],
            ['kode' => 'F40', 'nama' => 'Phobic anxiety disorders'],
            ['kode' => 'F41', 'nama' => 'Other anxiety disorders'],
            ['kode' => 'F42', 'nama' => 'Obsessive-compulsive disorder'],
            ['kode' => 'F43', 'nama' => 'Reaction to severe stress, and adjustment disorders'],
            ['kode' => 'F45', 'nama' => 'Somatoform disorders'],
            ['kode' => 'F48', 'nama' => 'Other neurotic disorders'],
            ['kode' => 'F50', 'nama' => 'Eating disorders'],
            ['kode' => 'F51', 'nama' => 'Non-organic sleep disorders'],
            ['kode' => 'F52', 'nama' => 'Sexual dysfunction not caused by organic disorder or disease'],
            ['kode' => 'F60', 'nama' => 'Specific personality disorders'],
            ['kode' => 'F61', 'nama' => 'Mixed and other personality disorders'],
            ['kode' => 'F62', 'nama' => 'Enduring personality changes, not attributable to brain damage and disease'],
            ['kode' => 'F63', 'nama' => 'Habit and impulse disorders'],
            ['kode' => 'F64', 'nama' => 'Gender identity disorders'],
            ['kode' => 'F65', 'nama' => 'Disorders of sexual preference'],
            ['kode' => 'F66', 'nama' => 'Psychological and behavioural disorders associated with sexual development and orientation'],
            ['kode' => 'F68', 'nama' => 'Other disorders of adult personality and behaviour'],
            ['kode' => 'F69', 'nama' => 'Unspecified disorder of adult personality and behaviour'],
            ['kode' => 'F70', 'nama' => 'Mild mental retardation'],
            ['kode' => 'F71', 'nama' => 'Moderate mental retardation'],
            ['kode' => 'F72', 'nama' => 'Severe mental retardation'],
            ['kode' => 'F73', 'nama' => 'Profound mental retardation'],
            ['kode' => 'F78', 'nama' => 'Other mental retardation'],
            ['kode' => 'F79', 'nama' => 'Unspecified mental retardation'],
            ['kode' => 'F80', 'nama' => 'Specific developmental disorders of speech and language'],
            ['kode' => 'F81', 'nama' => 'Specific developmental disorders of scholastic skills'],
            ['kode' => 'F82', 'nama' => 'Specific developmental disorder of motor function'],
            ['kode' => 'F83', 'nama' => 'Mixed specific developmental disorders'],
            ['kode' => 'F84', 'nama' => 'Pervasive developmental disorders'],
            ['kode' => 'F88', 'nama' => 'Other disorders of psychological development'],
            ['kode' => 'F89', 'nama' => 'Unspecified disorder of psychological development'],
            ['kode' => 'F90', 'nama' => 'Hyperkinetic disorders'],
            ['kode' => 'F91', 'nama' => 'Conduct disorders'],
            ['kode' => 'F92', 'nama' => 'Mixed disorders of conduct and emotions'],
            ['kode' => 'F93', 'nama' => 'Emotional disorders with onset specific to childhood'],
            ['kode' => 'F94', 'nama' => 'Disorders of social functioning with onset specific to childhood and adolescence'],
            ['kode' => 'F95', 'nama' => 'Tic disorders'],
            ['kode' => 'F98', 'nama' => 'Other behavioural and emotional disorders with onset usually occurring in childhood and adolescence'],
            ['kode' => 'F99', 'nama' => 'Unspecified mental disorder'],
        ];

        // Gunakan updateOrCreate agar tidak duplikat jika dijalankan berkali-kali
        foreach ($diagnoses as $diagnosis) {
            MasterDiagnosa::updateOrCreate(
                ['kode' => $diagnosis['kode']],
                ['nama' => $diagnosis['nama']]
            );
        }

        echo "\n✓ Seeding diagnosa ICD-10 WHO selesai (" . count($diagnoses) . " entri)\n";
    }
}
